### ISSUE TITLE
test_decimals_include_nan is flaky

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis-python#1033]
```
---------------------------------- Hypothesis ----------------------------------
You can add @seed(327206777863050896557169937789875330632) to this test or run pytest with --hypothesis-seed=327206777863050896557169937789875330632 to reproduce this failure.
__________________________ test_decimals_include_nan ___________________________
[gw8] linux -- Python 3.6.3 /usr/bin/python
tests/cover/test_numerics.py:88: in test_decimals_include_nan
    @given(decimals())
tests/common/utils.py:64: in inverted_test
    f(*arguments, **kwargs)
tests/cover/test_numerics.py:88: in test_decimals_include_nan
    @given(decimals())
E   hypothesis.errors.MultipleFailures: Hypothesis found 2 distinct failures.
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_decimals_include_nan(x=Decimal('sNaN'))
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 818, in run
    falsifying_example.__expected_traceback,
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 579, in execute
    result = self.test_runner(data, run)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 571, in run
    return test(*args, **kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/tests/cover/test_numerics.py", line 88, in test_decimals_include_nan
    @given(decimals())
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 518, in test
    result = self.test(*args, **kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/tests/cover/test_numerics.py", line 90, in test_decimals_include_nan
    assert not math.isnan(x)
  File "/usr/lib/python3.6/_pydecimal.py", line 1651, in __float__
    raise ValueError("Cannot convert signaling NaN to float")
ValueError: Cannot convert signaling NaN to float

Falsifying example: test_decimals_include_nan(x=Decimal('NaN'))
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 818, in run
    falsifying_example.__expected_traceback,
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 579, in execute
    result = self.test_runner(data, run)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 571, in run
    return test(*args, **kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/tests/cover/test_numerics.py", line 88, in test_decimals_include_nan
    @given(decimals())
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/src/hypothesis/core.py", line 518, in test
    result = self.test(*args, **kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.1/tests/cover/test_numerics.py", line 90, in test_decimals_include_nan
    assert not math.isnan(x)
AssertionError: assert not True
 +  where True = <built-in function isnan>(Decimal('NaN'))
 +    where <built-in function isnan> = math.isnan
```

**Comment by DRMacIver** [comment]
I think this is a genuine bug in the test. `math.isnan(x)` is not the correct way to check if a decimal is NaN, that would be `x.is_nan()`.

**Comment by DRMacIver** [comment]
I'm curious as to why your build is so much better at finding flaky test bugs than ours is though given that it's running the same tests!

**Comment by felixonmars** [comment]
I'm not sure, you can see my build script here: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-hypothesis

I made xdist to run 16 instances in parallel because our build machine has many cores, other parts are quite the same I guess :)
