### ISSUE TITLE
test_avoids_zig_zag_trap is flaky

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis-python#1087]
```
=================================== FAILURES ===================================
___________________________ test_avoids_zig_zag_trap ___________________________
[gw5] linux2 -- Python 2.7.14 /usr/bin/python2
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/tests/quality/test_zig_zagging.py", line 38, in test_avoids_zig_zag_trap
    @example((b'\x02', b'', 258))
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/src/hypothesis/core.py", line 988, in wrapped_test
    test_runner, test, wrapped_test, settings, arguments, kwargs
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/src/hypothesis/core.py", line 280, in execute_explicit_examples
    lambda data: test(*arguments, **example_kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/src/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/src/hypothesis/core.py", line 280, in <lambda>
    lambda data: test(*arguments, **example_kwargs)
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/tests/quality/test_zig_zagging.py", line 78, in test_avoids_zig_zag_trap
    b + hbytes([0]) + b + hbytes([1]) + marker))
  File "/build/python-hypothesis/src/hypothesis-python-3.44.23-py2/src/hypothesis/internal/compat.py", line 398, in __radd__
    assert isinstance(value, compatbytes)
AssertionError
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_avoids_zig_zag_trap(p=('\x01\x00', '', 20048))
```

**Comment by felixonmars** [comment]
Hrm, this seems more than a flaky issue. The test doesn't pass on Python 2.7.14 for >10 times in a row here...

**Comment by DRMacIver** [comment]
Hmm. That's weird. I can see why that might be failing, but I *can't* see why that might be failing for you and not for us.
