### ISSUE TITLE
hypothesis complains about random usage anywhere in any stack frame

### ISSUE THREAD

**Issue by Julian** [HypothesisWorks/hypothesis-python#303]
I'm not sure if this is intentional or not, if it's intentional behavior maybe this is just a confusing message, or maybe I'm just being unnecessarily nitpicky, but in a test that somewhere in some corner, happens to have a piece of code that uses `random.random` anywhere will trigger:

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/local/Cellar/pypy/5.0.0/libexec/lib-python/2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/Julian/Development//python-messages/messages/tests/test_fakes.py", line 14, in test_it_receives_events
    def test_it_receives_events(self, topic, events):
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/core.py", line 493, in wrapped_test
    runner.run()
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/internal/conjecture/engine.py", line 167, in run
    self._run()
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/internal/conjecture/engine.py", line 261, in _run
    self.test_function(data)
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/internal/conjecture/engine.py", line 67, in test_function
    self._test_function(data)
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/core.py", line 480, in evaluate_test_data
    HealthCheck.random_module,
  File "/Users/Julian/.local/share/virtualenvs/messages/site-packages/hypothesis/core.py", line 296, in fail_health_check
    raise FailedHealthCheck(message)
hypothesis.errors.FailedHealthCheck: Your test used the global random module. This is unlikely to work correctly. You should consider using the randoms() strategy from hypothesis.strategies instead. Alternatively, you can use the random_module() strategy to explicitly seed the random module.
See http://hypothesis.readthedocs.org/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.random_moduleto the suppress_health_check settings for this test.
```

when, looking at my test, I'm not invoking `random` anywhere, it's somewhere in a meaningless code path in a library that's being used deep inside my SUT, which doesn't affect the test output.

 I guess hypothesis is trying to save me from flaky tests, so I'd bet this is intentional, but maybe the error message could say "your test, or code it invoked", and possibly even hint at the stack frame, considering I bet hypothesis knows it if it detected someone touching the global random?

Alternatively, maybe cases where it's not the test itself doing it should only warn if hypothesis runs 2 examples and gets different results?

**Comment by Zac-HD** [comment]
This has been fixed for a while - I'm not sure exactly when, but the mechanism has been a no-op or some time and #970 deprecates even that.
