### ISSUE TITLE
Example for using settings with `@given` in the docs doesn’t seem to work

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis-python#328]
I’m looking at the “Seeing intermediate result” examples in the [settings docs](http://hypothesis.readthedocs.io/en/latest/settings.html).

If I try to work through the example, I get an error:

```pycon
>>> from hypothesis import given, settings, Verbosity
>>> from hypothesis.strategies import integers
>>> @given(integers(), settings=settings(verbosity=Verbosity.verbose))
... def test_foo(x):
...     assert x > 0
... 
>>> test_foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexwlchan/.virtualenvs/campug/lib/python3.5/site-packages/hypothesis/core.py", line 155, in wrapped_test
    raise InvalidArgument(message)
hypothesis.errors.InvalidArgument: cannot mix positional and keyword arguments to @given
```

I’m using Hypothesis 3.4.0 with Python 3.5 on OS&nbsp;X. I get the same error in Python&nbsp;2.7 and on Linux.

**Comment by DRMacIver** [comment]
Oops. That's out of date documentation. I'll fix it in a bit.

The new syntax to use is:

```python
@given(integers())
@settings(verbosity=Verbosity.verbose))
def test_foo(x):
     assert x > 0
```

(settings can go before or after given as you prefer)
