### ISSUE TITLE
Failures in teardown_example trigger an unhandled hypothesis exception

### ISSUE THREAD

**Issue by exarkun** [HypothesisWorks/hypothesis-python#402]
Consider

```
from hypothesis import given, strategies

from unittest import TestCase

class DemoTests(TestCase):
    def teardown_example(self, ignored):
        if getattr(self, "ran", False):
            self.fail("oh no bad stuff")

    @given(strategies.integers())
    def test_demo(self, i):
        self.ran = True
```

(this looks a little weird but it's meant to be a minimal representative example of how teardown_example might be used to make hypothesis work with testtools' `expectThat` feature - which is meant to fail the test after the test method finishes and not interrupt it with an exception)

This fails with:

```
$ trial demo.py
demo
  DemoTests
    test_demo ...                                                       [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "demo.py", line 11, in test_demo
    def test_demo(self, i):
  File ".../hypothesis/core.py", line 476, in wrapped_test
    runner.run()
  File ".../hypothesis/internal/conjecture/engine.py", line 191, in run
    self._run()
  File ".../hypothesis/internal/conjecture/engine.py", line 392, in _run
    self.last_data.buffer[v:]
  File ".../hypothesis/internal/conjecture/engine.py", line 176, in incorporate_new_buffer
    self.test_function(data)
  File ".../hypothesis/internal/conjecture/engine.py", line 81, in test_function
    self._test_function(data)
  File ".../hypothesis/core.py", line 464, in evaluate_test_data
    data.mark_interesting()
  File ".../hypothesis/internal/conjecture/data.py", line 166, in mark_interesting
    self.__assert_not_frozen('mark_interesting')
  File ".../hypothesis/internal/conjecture/data.py", line 82, in __assert_not_frozen
    name,))
hypothesis.errors.Frozen: Cannot call mark_interesting on frozen TestData

demo.DemoTests.test_demo
-------------------------------------------------------------------------------
Ran 1 tests in 0.251s

FAILED (errors=1)
```

Using Hypothesis 3.6.0, Python 2.7.12.

**Comment by Zac-HD** [comment]
With Hypothesis 3.42, I get:

```
    from hypothesis import given, strategies
    import unittest
    class DemoTests(unittest.TestCase):
        def teardown_example(self, ignored):
            if getattr(self, "ran", False):
                self.fail("oh no bad stuff")

        @given(strategies.integers())
        def test_demo(self, i):
            self.ran = True
    unittest.main()

    Falsifying example: test_demo(self=<__main__.DemoTests testMethod=test_demo>, i=0)
    F
    ======================================================================
    FAIL: test_demo (__main__.DemoTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
        ...
    AssertionError: oh no bad stuff

    ----------------------------------------------------------------------
    Ran 1 test in 0.016s
```
