### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by jibe-b** [HypothesisWorks/hypothesis-python#445]
## Installation process

I've been following http://h.readthedocs.io/en/latest/developing/install/website/#installing-the-services on Ubuntu 16.04 server.

## Log

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/h/h/__main__.py", line 6, in <module>
    main()
  File "h/cli/__init__.py", line 74, in main
    cli(prog_name='hypothesis', obj={})
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/h/.venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "h/cli/commands/devserver.py", line 91, in devserver
    m.loop()
  File "/root/h/.venv/local/lib/python2.7/site-packages/honcho/manager.py", line 116, in loop
    self._printer.write(msg)
  File "/root/h/.venv/local/lib/python2.7/site-packages/honcho/printer.py", line 46, in write
    self.output.write(prefix + line + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bc' in position 68: ordinal not in range(128)

I'll try to see if I can solve it by my own.

**Comment by alexwlchan** [comment]
Hi @jibe-b,

I think you have the wrong repository – this is for a Python testing library, whereas those docs are for a web annotation framework. You probably want to refile your issue at https://github.com/hypothesis/h/issues.

(Yes, I know it’s confusing!)

**Comment by jibe-b** [comment]
You're right, sorry.
