### ISSUE TITLE
pytest's switch to setuptools-scm breaks version check

### ISSUE THREAD

**Issue by The-Compiler** [HypothesisWorks/hypothesis-python#611]
With the latest pytest `features` branch with https://github.com/pytest-dev/pytest/pull/1834 in, I get:

```
Traceback (most recent call last):
  File "./.venv/bin/pytest", line 11, in <module>
    load_entry_point('pytest', 'console_scripts', 'pytest')()
  File "/home/florian/proj/pytest/_pytest/config.py", line 48, in main
    config = _prepareconfig(args, plugins)
  File "/home/florian/proj/pytest/_pytest/config.py", line 157, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/home/florian/proj/pytest/_pytest/helpconfig.py", line 34, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 279, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/florian/proj/pytest/_pytest/config.py", line 926, in pytest_cmdline_parse
    self.parse(args)
  File "/home/florian/proj/pytest/_pytest/config.py", line 1084, in parse
    self._preparse(args, addopts=addopts)
  File "/home/florian/proj/pytest/_pytest/config.py", line 1046, in _preparse
    self.pluginmanager.load_setuptools_entrypoints(entrypoint_name)
  File "/home/florian/proj/pytest/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/florian/proj/pytest/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.6/site-packages/hypothesis/extra/pytestplugin.py", line 32, in <module>
    re.sub('-.+', '', pytest.__version__).split('.')[:3]
ValueError: invalid literal for int() with base 10: 'unknown'
```

**Comment by nicoddemus** [comment]
Hmmm are you using a development version @The-Compiler? Because regardless it should work if you do a `pip install -e .` on Pytest; this will generate the `_version.py` file...
