### ISSUE TITLE
pytest Python 3.4 failure since 3.8.3

### ISSUE THREAD

**Issue by lordi** [HypothesisWorks/hypothesis-python#691]
Since hypothesis 3.8.3, the following failure occurs in our travis checks:
```
============================= test session starts ==============================
platform linux -- Python 3.4.2 -- py-1.4.26 -- pytest-2.6.4
plugins: hypothesis
collected 38 items 

tests/test_crypto.py 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/main.py", line 142, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/runner.py", line 72, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/runner.py", line 111, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/main.py", line 167, in call_matching_hooks
INTERNALERROR>     return hookmethod.pcall(plugins, **kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 417, in pcall
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/_pytest/core.py", line 325, in execute
INTERNALERROR>     fin()
INTERNALERROR>   File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/hypothesis/extra/pytestplugin.py", line 93, in pytest_runtest_makereport
INTERNALERROR>     report = (yield).get_result()
INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'get_result'
```

Do you need more information?

**Comment by The-Compiler** [comment]
You're using a version of pytest which is almost three years old - you might want to upgrade to something more recent.

**Comment by alexwlchan** [comment]
Yep, you need to upgrade to a newer version of pytest. We only support pytest 2.8.0 or later (where “supported” is defined by what we test with in our CI).

I notice you're not pinning [the version of pytest in your setup.py](https://github.com/syncrypt/client/blob/master/setup.py#L140) – is there anything stopping you from upgrading to a newer release?

As to why this starts happening in 3.8.3: before that, we had a check that would cause Hypothesis to skip loading our plugin for pytest <2.7. We removed this check in #612 because it was causing problems when pytest used a non-standing versioning scheme – so previously I don’t think these tests would have run at all?

**Comment by lordi** [comment]
Tests ran fine before.

Thanks for the help, I guess I'll pin the pytest version.

**Comment by DRMacIver** [comment]
Yeah, the tests would have run before, just without any of the special pytest support that makes it slightly more convenient.

Agreed that the solution here is to update pytest though.
