### ISSUE TITLE
UnicodeEncodeError being raised in py2 when running st.example()

### ISSUE THREAD

**Issue by CodyKochmann** [HypothesisWorks/hypothesis-python#757]
Normally I hate it when people just paste a traceback and don't have much to say in terms of the issue, but I really don't know how to fix this with hypothesis. 

This is happening in python2 and I cant quite find a way to get hypothesis to explain any further.

When I run `mystrategy.example()` which is built with 
```python
mystrategy = st.none().map(my_garbage_generator.send)
``` 
I end up getting the following exception after a few runs:

```
Traceback (most recent call last):
  File "/Users/cody/git/battle_tested/battle_tested/loaded_modules.py", line 246, in <module>
    out = garbage.example()
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/strategies.py", line 139, in example
    verbosity=Verbosity.quiet,
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 759, in find
    runner.run()
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/engine.py", line 240, in run
    self._run()
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/engine.py", line 460, in _run
    self.new_buffer()
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/engine.py", line 96, in new_buffer
    self.test_function(self.last_data)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/engine.py", line 102, in test_function
    self._test_function(data)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 729, in template_condition
    data.note(result)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 100, in note
    value = unicode_safe_repr(value)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/compat.py", line 182, in unicode_safe_repr
    r = repr(x)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u59a8' in position 10: ordinal not in range(128)
```
 
Any help in this issue would be deeply appreciated.

**Comment by alexwlchan** [comment]
Two questions to start with:

* Which versions of Hypothesis and Python are you using?
* What’s `my_garbage_generator`?

**Comment by DRMacIver** [comment]
I think the problem is going to be in the values that you're returning from your strategy. They're likely return a `unicode` object as their `__repr__`, which on Python 2 then gets turned into a `str` by encoding it as ascii when Hypothesis calls repr on it.

Without the code it's hard to say for sure. what's going on though. Maybe try running it under pdb and see if anything jumps out at you?

**Comment by CodyKochmann** [comment]
My library is blowing up hypothesis when its running only in python2.7 (python3 runs fine). These issues started showing up once `3.14.0` was released.

I did what I could to replicate the error in `py2.7` with `3.14.1` installed and ran into this before I could get to the `UnicodeEncodeError` (this also runs fine in `py3`):

```python
from hypothesis import strategies as st, given

@given(st.fractions())
def test(i):
    i=i

test()
```
Which results in:
```python
Traceback (most recent call last):
  File "/Users/cody/Desktop/hypothesis_bug_hunt.py", line 7, in <module>
    test()
  File "/Users/cody/Desktop/hypothesis_bug_hunt.py", line 4, in test
    def test(i):
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 695, in wrapped_test
    random, settings, test_runner, search_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 328, in perform_health_checks
    escalate_hypothesis_internal_error()
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 314, in perform_health_checks
    lambda *args, **kwargs: None,
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/executors.py", line 58, in default_new_style_executor
    return function(data)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/core.py", line 104, in run
    args, kwargs = data.draw(search_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/lazy.py", line 135, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 63, in do_draw
    data.draw(e) for e in self.element_strategies
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 59, in newtuple
    return tuple(xs)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 63, in <genexpr>
    data.draw(e) for e in self.element_strategies
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/strategies.py", line 346, in do_draw
    return self.pack(self.mapped_strategy.do_draw(data))
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/lazy.py", line 135, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/strategies.py", line 346, in do_draw
    return self.pack(self.mapped_strategy.do_draw(data))
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 63, in do_draw
    data.draw(e) for e in self.element_strategies
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 59, in newtuple
    return tuple(xs)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/collections.py", line 63, in <genexpr>
    data.draw(e) for e in self.element_strategies
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/lazy.py", line 135, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/flatmapped.py", line 46, in do_draw
    return data.draw(self.expand(source))
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/internal/conjecture/data.py", line 114, in draw
    return strategy.do_draw(self)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/lazy.py", line 135, in do_draw
    return data.draw(self.wrapped_strategy)
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/searchstrategy/lazy.py", line 99, in wrapped_strategy
    for k, v in self.__kwargs.items()})
  File "/Users/cody/Library/Python/2.7/lib/python/site-packages/hypothesis/strategies.py", line 798, in builds
    for ms in set(hints) & (required or set()):
TypeError: 'NoneType' object is not iterable
```

**Comment by DRMacIver** [comment]
@CodyKochmann Huh. At first I couldn't reproduce this, but it looks like the problem with Python 2.7 with the typing module installed. @Zac-HD I thought we had tests for this?

**Comment by DRMacIver** [comment]
@CodyKochmann OK if you update to the latest version of Hypothesis the `TypeError` should be fixed now.

**Comment by CodyKochmann** [comment]
Looks like everything works again! Thanks :)

**Comment by DRMacIver** [comment]
@CodyKochmann Note that we haven't done anything that should affect your initial unicode error! The only thing that got fixed was the TypeError your reported after.
