### ISSUE TITLE
Tests fail with execnet 1.3.0

### ISSUE THREAD

**Issue by nehaljwani** [HypothesisWorks/hypothesis-python#974]
```
12:04:46
============================= test session starts ==============================
12:04:48
platform linux -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
12:04:48
cachedir: .cache
12:04:48
rootdir: /tmp/build/80754af9/hypothesis_1510984556704/test_tmp/src, inifile: tox.ini
12:04:48
plugins: xdist-1.17.1, hypothesis-3.37.0, flaky-3.4.0
12:04:48
gw0 I / gw1 IINTERNALERROR> Traceback (most recent call last):
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/main.py", line 108, in wrap_session
12:04:48
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
12:04:48
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
12:04:48
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
12:04:48
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
12:04:48
INTERNALERROR>     res = hook_impl.function(*args)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/xdist/dsession.py", line 507, in pytest_sessionstart
12:04:48
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/xdist/slavemanage.py", line 64, in setup_nodes
12:04:48
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/xdist/slavemanage.py", line 69, in setup_node
12:04:48
INTERNALERROR>     self.config.hook.pytest_xdist_newgateway(gateway=gw)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
12:04:48
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
12:04:48
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
12:04:48
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
12:04:48
INTERNALERROR>     res = hook_impl.function(*args)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/xdist/dsession.py", line 766, in pytest_xdist_newgateway
12:04:48
INTERNALERROR>     rinfo = gateway._rinfo()
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/execnet/gateway.py", line 70, in _rinfo
12:04:48
INTERNALERROR>     ch = self.remote_exec(rinfo_source)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/execnet/gateway.py", line 110, in remote_exec
12:04:48
INTERNALERROR>     source = _source_of_function(source)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/execnet/gateway.py", line 173, in _source_of_function
12:04:48
INTERNALERROR>     args, varargs, keywords, defaults = inspect.getargspec(function)
12:04:48
INTERNALERROR>   File "/tmp/build/80754af9/hypothesis_1510984556704/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/inspect.py", line 1068, in getargspec
12:04:48
INTERNALERROR>     DeprecationWarning, stacklevel=2)
12:04:48
INTERNALERROR> DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```

**Comment by Zac-HD** [comment]
Not a bug - since #931, we run with `DeprecationWarning`s as errors and this requires a newer version of  `execnet`.

If you want to run tests locally but *can't* `pip install execnet >= 1.4` for some reason, you could patch `tests/common/setup.py` to avoid setting this option.
